/* Auto-generated by genmsg_cpp for file /home/ubuntu/workspace/sandbox/scarborough/msg/YPR.msg */
#ifndef SCARBOROUGH_MESSAGE_YPR_H
#define SCARBOROUGH_MESSAGE_YPR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace scarborough
{
template <class ContainerAllocator>
struct YPR_ {
  typedef YPR_<ContainerAllocator> Type;

  YPR_()
  : YPR()
  {
    YPR.assign(0.0);
  }

  YPR_(const ContainerAllocator& _alloc)
  : YPR()
  {
    YPR.assign(0.0);
  }

  typedef boost::array<double, 3>  _YPR_type;
  boost::array<double, 3>  YPR;


  typedef boost::shared_ptr< ::scarborough::YPR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scarborough::YPR_<ContainerAllocator>  const> ConstPtr;
}; // struct YPR
typedef  ::scarborough::YPR_<std::allocator<void> > YPR;

typedef boost::shared_ptr< ::scarborough::YPR> YPRPtr;
typedef boost::shared_ptr< ::scarborough::YPR const> YPRConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::scarborough::YPR_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::scarborough::YPR_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace scarborough

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::scarborough::YPR_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::scarborough::YPR_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::scarborough::YPR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "932fd5a1b0efdafe2ac005ed95f2acb3";
  }

  static const char* value(const  ::scarborough::YPR_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x932fd5a1b0efdafeULL;
  static const uint64_t static_value2 = 0x2ac005ed95f2acb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::scarborough::YPR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "scarborough/YPR";
  }

  static const char* value(const  ::scarborough::YPR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::scarborough::YPR_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[3] YPR\n\
";
  }

  static const char* value(const  ::scarborough::YPR_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::scarborough::YPR_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::scarborough::YPR_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.YPR);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct YPR_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scarborough::YPR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::scarborough::YPR_<ContainerAllocator> & v) 
  {
    s << indent << "YPR[]" << std::endl;
    for (size_t i = 0; i < v.YPR.size(); ++i)
    {
      s << indent << "  YPR[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.YPR[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // SCARBOROUGH_MESSAGE_YPR_H

