# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scarborough/Desired_Directions.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Desired_Directions(genpy.Message):
  _md5sum = "b52e1a589c56fcea3b3260406f15fe61"
  _type = "scarborough/Desired_Directions"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32[3] rotation
int32 throttle
float32 depth
"""
  __slots__ = ['rotation','throttle','depth']
  _slot_types = ['float32[3]','int32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rotation,throttle,depth

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Desired_Directions, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.rotation is None:
        self.rotation = [0.,0.,0.]
      if self.throttle is None:
        self.throttle = 0
      if self.depth is None:
        self.depth = 0.
    else:
      self.rotation = [0.,0.,0.]
      self.throttle = 0
      self.depth = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_3f.pack(*self.rotation))
      _x = self
      buff.write(_struct_if.pack(_x.throttle, _x.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 12
      self.rotation = _struct_3f.unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.throttle, _x.depth,) = _struct_if.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.rotation.tostring())
      _x = self
      buff.write(_struct_if.pack(_x.throttle, _x.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 12
      self.rotation = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 8
      (_x.throttle, _x.depth,) = _struct_if.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3f = struct.Struct("<3f")
_struct_if = struct.Struct("<if")
